group=data

[file]
filename=shaders/bloom_upsample.frag
alias=bloom_upsample.frag

[file]
filename=shaders/bloom_upsample.vert
alias=bloom_upsample.vert

[file]
filename=shaders/bloom_downsample.frag
alias=bloom_downsample.frag

[file]
filename=shaders/bloom_downsample.vert
alias=bloom_downsample.vert

[file]
filename=shaders/bloom_final.frag
alias=bloom_final.frag

[file]
filename=shaders/bloom_final.vert
alias=bloom_final.vert